//
//  Copyright (c) 2023 Katoemba Software, (https://rigelian.net/)
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
//
//  Generated by SwiftUPnP/UPnPCodeGenerator
//

import Foundation
import Combine
import XMLCoder
import os.log

public class OpenHomeVolume1Service: UPnPService {
	struct Envelope<T: Codable>: Codable {
		enum CodingKeys: String, CodingKey {
			case body = "s:Body"
		}

		var body: T
	}

	public struct CharacteristicsResponse: Codable {
		enum CodingKeys: String, CodingKey {
			case volumeMax = "VolumeMax"
			case volumeUnity = "VolumeUnity"
			case volumeSteps = "VolumeSteps"
			case volumeMilliDbPerStep = "VolumeMilliDbPerStep"
			case balanceMax = "BalanceMax"
			case fadeMax = "FadeMax"
		}

		public var volumeMax: UInt32
		public var volumeUnity: UInt32
		public var volumeSteps: UInt32
		public var volumeMilliDbPerStep: UInt32
		public var balanceMax: UInt32
		public var fadeMax: UInt32

		public func log(deep: Bool = false, indent: Int = 0) {
			Logger.swiftUPnP.debug("\(Logger.indent(indent))CharacteristicsResponse {")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))volumeMax: \(volumeMax)")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))volumeUnity: \(volumeUnity)")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))volumeSteps: \(volumeSteps)")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))volumeMilliDbPerStep: \(volumeMilliDbPerStep)")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))balanceMax: \(balanceMax)")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))fadeMax: \(fadeMax)")
			Logger.swiftUPnP.debug("\(Logger.indent(indent))}")
		}
	}
	public func characteristics(log: UPnPService.MessageLog = .none) async throws -> CharacteristicsResponse {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:Characteristics"
				case response = "u:CharacteristicsResponse"
			}

			var action: SoapAction?
			var response: CharacteristicsResponse?
		}
		let result: Envelope<Body> = try await postWithResult(action: "Characteristics", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)

		guard let response = result.body.response else { throw ServiceParseError.noValidResponse }
		return response
	}

	public func setVolume(value: UInt32, log: UPnPService.MessageLog = .none) async throws {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
				case value = "Value"
			}

			@Attribute var urn: String
			public var value: UInt32
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:SetVolume"
			}

			var action: SoapAction
		}
		try await post(action: "SetVolume", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType), value: value))), log: log)
	}

	public func volumeInc(log: UPnPService.MessageLog = .none) async throws {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:VolumeInc"
			}

			var action: SoapAction
		}
		try await post(action: "VolumeInc", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)
	}

	public func volumeDec(log: UPnPService.MessageLog = .none) async throws {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:VolumeDec"
			}

			var action: SoapAction
		}
		try await post(action: "VolumeDec", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)
	}

	public struct VolumeResponse: Codable {
		enum CodingKeys: String, CodingKey {
			case value = "Value"
		}

		public var value: UInt32

		public func log(deep: Bool = false, indent: Int = 0) {
			Logger.swiftUPnP.debug("\(Logger.indent(indent))VolumeResponse {")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))value: \(value)")
			Logger.swiftUPnP.debug("\(Logger.indent(indent))}")
		}
	}
	public func volume(log: UPnPService.MessageLog = .none) async throws -> VolumeResponse {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:Volume"
				case response = "u:VolumeResponse"
			}

			var action: SoapAction?
			var response: VolumeResponse?
		}
		let result: Envelope<Body> = try await postWithResult(action: "Volume", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)

		guard let response = result.body.response else { throw ServiceParseError.noValidResponse }
		return response
	}

	public func setBalance(value: Int32, log: UPnPService.MessageLog = .none) async throws {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
				case value = "Value"
			}

			@Attribute var urn: String
			public var value: Int32
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:SetBalance"
			}

			var action: SoapAction
		}
		try await post(action: "SetBalance", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType), value: value))), log: log)
	}

	public func balanceInc(log: UPnPService.MessageLog = .none) async throws {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:BalanceInc"
			}

			var action: SoapAction
		}
		try await post(action: "BalanceInc", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)
	}

	public func balanceDec(log: UPnPService.MessageLog = .none) async throws {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:BalanceDec"
			}

			var action: SoapAction
		}
		try await post(action: "BalanceDec", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)
	}

	public struct BalanceResponse: Codable {
		enum CodingKeys: String, CodingKey {
			case value = "Value"
		}

		public var value: Int32

		public func log(deep: Bool = false, indent: Int = 0) {
			Logger.swiftUPnP.debug("\(Logger.indent(indent))BalanceResponse {")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))value: \(value)")
			Logger.swiftUPnP.debug("\(Logger.indent(indent))}")
		}
	}
	public func balance(log: UPnPService.MessageLog = .none) async throws -> BalanceResponse {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:Balance"
				case response = "u:BalanceResponse"
			}

			var action: SoapAction?
			var response: BalanceResponse?
		}
		let result: Envelope<Body> = try await postWithResult(action: "Balance", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)

		guard let response = result.body.response else { throw ServiceParseError.noValidResponse }
		return response
	}

	public func setFade(value: Int32, log: UPnPService.MessageLog = .none) async throws {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
				case value = "Value"
			}

			@Attribute var urn: String
			public var value: Int32
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:SetFade"
			}

			var action: SoapAction
		}
		try await post(action: "SetFade", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType), value: value))), log: log)
	}

	public func fadeInc(log: UPnPService.MessageLog = .none) async throws {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:FadeInc"
			}

			var action: SoapAction
		}
		try await post(action: "FadeInc", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)
	}

	public func fadeDec(log: UPnPService.MessageLog = .none) async throws {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:FadeDec"
			}

			var action: SoapAction
		}
		try await post(action: "FadeDec", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)
	}

	public struct FadeResponse: Codable {
		enum CodingKeys: String, CodingKey {
			case value = "Value"
		}

		public var value: Int32

		public func log(deep: Bool = false, indent: Int = 0) {
			Logger.swiftUPnP.debug("\(Logger.indent(indent))FadeResponse {")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))value: \(value)")
			Logger.swiftUPnP.debug("\(Logger.indent(indent))}")
		}
	}
	public func fade(log: UPnPService.MessageLog = .none) async throws -> FadeResponse {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:Fade"
				case response = "u:FadeResponse"
			}

			var action: SoapAction?
			var response: FadeResponse?
		}
		let result: Envelope<Body> = try await postWithResult(action: "Fade", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)

		guard let response = result.body.response else { throw ServiceParseError.noValidResponse }
		return response
	}

	public func setMute(value: Bool, log: UPnPService.MessageLog = .none) async throws {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
				case value = "Value"
			}

			@Attribute var urn: String
			public var value: Bool
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:SetMute"
			}

			var action: SoapAction
		}
		try await post(action: "SetMute", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType), value: value))), log: log)
	}

	public struct MuteResponse: Codable {
		enum CodingKeys: String, CodingKey {
			case value = "Value"
		}

		public var value: Bool

		public func log(deep: Bool = false, indent: Int = 0) {
			Logger.swiftUPnP.debug("\(Logger.indent(indent))MuteResponse {")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))value: \(value == true ? "true" : "false")")
			Logger.swiftUPnP.debug("\(Logger.indent(indent))}")
		}
	}
	public func mute(log: UPnPService.MessageLog = .none) async throws -> MuteResponse {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:Mute"
				case response = "u:MuteResponse"
			}

			var action: SoapAction?
			var response: MuteResponse?
		}
		let result: Envelope<Body> = try await postWithResult(action: "Mute", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)

		guard let response = result.body.response else { throw ServiceParseError.noValidResponse }
		return response
	}

	public struct VolumeLimitResponse: Codable {
		enum CodingKeys: String, CodingKey {
			case value = "Value"
		}

		public var value: UInt32

		public func log(deep: Bool = false, indent: Int = 0) {
			Logger.swiftUPnP.debug("\(Logger.indent(indent))VolumeLimitResponse {")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))value: \(value)")
			Logger.swiftUPnP.debug("\(Logger.indent(indent))}")
		}
	}
	public func volumeLimit(log: UPnPService.MessageLog = .none) async throws -> VolumeLimitResponse {
		struct SoapAction: Codable {
			enum CodingKeys: String, CodingKey {
				case urn = "xmlns:u"
			}

			@Attribute var urn: String
		}
		struct Body: Codable {
			enum CodingKeys: String, CodingKey {
				case action = "u:VolumeLimit"
				case response = "u:VolumeLimitResponse"
			}

			var action: SoapAction?
			var response: VolumeLimitResponse?
		}
		let result: Envelope<Body> = try await postWithResult(action: "VolumeLimit", envelope: Envelope(body: Body(action: SoapAction(urn: Attribute(serviceType)))), log: log)

		guard let response = result.body.response else { throw ServiceParseError.noValidResponse }
		return response
	}

}

// Event parser
extension OpenHomeVolume1Service {
	public struct State: Codable {
		enum CodingKeys: String, CodingKey {
			case volume = "Volume"
			case mute = "Mute"
			case balance = "Balance"
			case fade = "Fade"
			case volumeLimit = "VolumeLimit"
			case volumeMax = "VolumeMax"
			case volumeUnity = "VolumeUnity"
			case volumeSteps = "VolumeSteps"
			case volumeMilliDbPerStep = "VolumeMilliDbPerStep"
			case balanceMax = "BalanceMax"
			case fadeMax = "FadeMax"
		}

		public var volume: UInt32?
		public var mute: Bool?
		public var balance: Int32?
		public var fade: Int32?
		public var volumeLimit: UInt32?
		public var volumeMax: UInt32?
		public var volumeUnity: UInt32?
		public var volumeSteps: UInt32?
		public var volumeMilliDbPerStep: UInt32?
		public var balanceMax: UInt32?
		public var fadeMax: UInt32?

		public func log(deep: Bool = false, indent: Int = 0) {
			Logger.swiftUPnP.debug("\(Logger.indent(indent))OpenHomeVolume1ServiceState {")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))volume: \(volume ?? 0)'")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))mute: \((mute == nil) ? "nil" : (mute! == true ? "true" : "false"))")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))balance: \(balance ?? 0)'")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))fade: \(fade ?? 0)'")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))volumeLimit: \(volumeLimit ?? 0)'")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))volumeMax: \(volumeMax ?? 0)'")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))volumeUnity: \(volumeUnity ?? 0)'")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))volumeSteps: \(volumeSteps ?? 0)'")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))volumeMilliDbPerStep: \(volumeMilliDbPerStep ?? 0)'")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))balanceMax: \(balanceMax ?? 0)'")
			Logger.swiftUPnP.debug("\(Logger.indent(indent+1))fadeMax: \(fadeMax ?? 0)'")
			Logger.swiftUPnP.debug("\(Logger.indent(indent))}")
		}
	}

	public func state(xml: Data) throws -> State {
		struct PropertySet: Codable {
			var property: [State]
		}

		let decoder = XMLDecoder()
		decoder.shouldProcessNamespaces = true
		let propertySet = try decoder.decode(PropertySet.self, from: xml)

		return propertySet.property.reduce(State()) { partialResult, property in
			var result = partialResult
			if let volume = property.volume {
				result.volume = volume
			}
			if let mute = property.mute {
				result.mute = mute
			}
			if let balance = property.balance {
				result.balance = balance
			}
			if let fade = property.fade {
				result.fade = fade
			}
			if let volumeLimit = property.volumeLimit {
				result.volumeLimit = volumeLimit
			}
			if let volumeMax = property.volumeMax {
				result.volumeMax = volumeMax
			}
			if let volumeUnity = property.volumeUnity {
				result.volumeUnity = volumeUnity
			}
			if let volumeSteps = property.volumeSteps {
				result.volumeSteps = volumeSteps
			}
			if let volumeMilliDbPerStep = property.volumeMilliDbPerStep {
				result.volumeMilliDbPerStep = volumeMilliDbPerStep
			}
			if let balanceMax = property.balanceMax {
				result.balanceMax = balanceMax
			}
			if let fadeMax = property.fadeMax {
				result.fadeMax = fadeMax
			}
			return result
		}
	}

	public var stateSubject: AnyPublisher<State, Never> {
		subscribedEventPublisher
			.compactMap { [weak self] in
				guard let self else { return nil }

				return try? self.state(xml: $0)
			}
			.eraseToAnyPublisher()
	}
}
